### ISSUE TITLE
[EXCEPTION] Profile overlay “cannot access disposed object”

### ISSUE THREAD

**Issue by Schmitin** [BestOfAllCoding/SUPLauncher-Reborn#17]
**How to reproduce:**
Ctrl + C a steam ID multiple times in quick succession
**Screenshots:** If you can
![image](https://user-images.githubusercontent.com/59183604/183228972-a4299cdc-c5c6-4601-a6c4-aac6d6f8a3ac.png)

**Exception Message:**
```
Cannot access a disposed object.
Object name: 'OverlayProfile'.


Stack trace:
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Form.set_Opacity(Double value)
   at SUPLauncher_Reborn.OverlayProfile.fadeIn(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Schmitin** [comment]
Note: Issue is with Staff Overlay enabled. Forgot to mention.

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/c878631473b564ea669c3c5736fbc8ecf3c336b6

**Comment by Schmitin** [comment]
Also pog.
