### ISSUE TITLE
[EXCEPTION]

### ISSUE THREAD

**Issue by JanTuck** [BestOfAllCoding/SUPLauncher-Reborn#33]
**How to reproduce:**
No clue
**Screenshots:** If you can
No clue

**Exception Message:**
Access is denied

Stack trace:
   at System.Diagnostics.Process.Kill()
   at SUPLauncher_Reborn.frm_main.validateCheck(Server server, Int32 check)
   at SUPLauncher_Reborn.frm_main.validateCheck(Server server, Int32 check)
   at SUPLauncher_Reborn.frm_main.validateCheck(Server server, Int32 check)
   at SUPLauncher_Reborn.frm_main.connect(Server server)
   at SUPLauncher_Reborn.ServerPanel.<>c__DisplayClass1_0.<updateServer>b__0(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by aidanH39** [comment]
Errm. Is this using the AFK mode? What I can see from exception I think. Or maybe closing the program? Cant tell much. What was you doing to receive this exception

**Comment by JanTuck** [comment]
> Errm. Is this using the AFK mode? What I can see from exception I think. Or maybe closing the program? Cant tell much. What was you doing to receive this exception

Not really has just been jumping around all day.

**Comment by aidanH39** [comment]
Errm. Have you tried launching into a server when AFK mode was enabled by any chance? Might be a bug there

**Comment by JanTuck** [comment]
> Errm. Have you tried launching into a server when AFK mode was enabled by any chance? Might be a bug there

Nope have never had a use for it on CWRP

**Comment by aidanH39** [comment]
Mm. I’ll have to check it out once I get back. If it continues when you have it open. A restart should stop it popping up.
