### ISSUE TITLE
[EXCEPTION]

### ISSUE THREAD

**Issue by Schmitin** [BestOfAllCoding/SUPLauncher-Reborn#37]
**How to reproduce:**
Exception occurred on launch.
**Screenshots:** If you can
N/A
**Exception Message:**
The remote server returned an error: (403) Forbidden.

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at SUPLauncher_Reborn.SuperiorServers.getProfile(String id) in G:\Github\SUPLauncher-Reborn\SUPLauncher-Reborn\SUPLauncher-Reborn\SuperiorServers.cs:line 87
   at SUPLauncher_Reborn.frm_main.frm_main_Load(Object sender, EventArgs e) in G:\Github\SUPLauncher-Reborn\SUPLauncher-Reborn\SUPLauncher-Reborn\Main.cs:line 101
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by aidanH39** [comment]
Does this occur regularly by any chance? Or a one time thing? I believe this may of been a one time api request that may of got denied for some reason. 

I will add some error handling in for this though instead of giving a exception.
